---
- name: "Create {{ tron_user_name }} user"
  user:
    name: "{{ tron_user_name }}"
    home: "/home/{{ tron_user_name }}"
    shell: /bin/bash
    system: yes

- name: "Creates directory"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ tron_user_name }}"
    group: "{{ tron_user_name }}"
    mode: 0755
    recurse: yes
  loop:
    - "{{ tron_datadir }}"
    - "{{ tron_service_dir }}"

- name: "Enable linger for {{ tron_user_name }}"
  command: "loginctl enable-linger {{tron_user_name}}"

- name: "Download FullNode.jar"
  get_url:
    url: "{{ tron_fullnode_url }}"
    dest: "{{ tron_root }}"
    owner: "{{ tron_user_name }}"
    group: "{{ tron_user_name }}"
    mode: 0755  

- name: "Download main net config"
  get_url:
    url: "{{ tron_config_url }}"
    dest: "{{ tron_root }}"
    owner: "{{ tron_user_name }}"
    group: "{{ tron_user_name }}"
    mode: 0755
